### ISSUE TITLE
Not working correctly after reboot

### ISSUE THREAD

**Issue by dordio** [glsorre/amethystwindows#40]
**Describe the bug**
The app works fine, until I reboot the computer. After that I'm no longer able to move windows between monitors using mod2 + J or mod2 + K.

**To Reproduce**
1. Install the app, it works fine
2. Reboot the computer
3. App won't work correctly anymore

**Expected behavior**
I should be abel to move windows to my other monitor using either mod2 + J or mod2 + K. But once I restart Windows this doesn't work anymore.
I also noticed that, after a reboot, sometimes pressing mod2 + J or mod2 + K swaps the focused window with the main window (the behavior of mod1 + ENTER)

**Desktop (please complete the following information):**
 - OS: Windows 10 - 19043.1055
 - Vivaldi
 - Version 4.0.2312.27

**Comment by glsorre** [comment]
Hello @dordio, let me do an investigation and I will come back to you. Are you customizing keys?

**Comment by dordio** [comment]
Sorry for the late response. No, I'm not customizing keys.
I should add that I'm using a Razer Huntsman Mini, maybe that will help.

**Comment by tgolsson** [comment]
I've got exactly the same problem - first install worked perfectly, updated and rebooted and it doesn't work anymore. To add some detail, the list of windows is empty in the Amethyst window, and in the Event Viewer I find the following call stack:

```
Application: AmethystWindowsSystray.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.InvalidCastException
   at WindowsDesktop.Internal.IServiceProvider10.QueryService(System.Guid ByRef, System.Guid ByRef)
   at WindowsDesktop.Internal.DesktopManager..cctor()

Exception Info: System.TypeInitializationException
   at WindowsDesktop.VirtualDesktop.get_Current()
   at DesktopWindowManager.Internal.DesktopWindow.GetVirtualDesktop()
   at DesktopWindowManager.Internal.DesktopWindow.GetInfo()
   at AmethystWindowsSystray.DesktopWindowsManager.<GetWindows>b__21_0(Vanara.PInvoke.HWND, IntPtr)
   at Vanara.PInvoke.User32.EnumWindows(EnumWindowsProc, IntPtr)
   at AmethystWindowsSystray.DesktopWindowsManager.GetWindows()
   at AmethystWindowsSystray.SystrayContext+<Initialize>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by glsorre** [comment]
Hello @tgolsson  thank you for the report. I will try to gitve it alook during the weekend.

**Comment by silver-dragon** [comment]
I just wanted to chime in and say I am having the same issue. Currently, the only workaround I have found is to uninstall and reinstall amethyst after a reboot.

**Comment by dordio** [comment]
> I just wanted to chime in and say I am having the same issue. Currently, the only workaround I have found is to uninstall and reinstall amethyst after a reboot.

And if you reboot after that it still works correctly?

**Comment by silver-dragon** [comment]
> And if you reboot after that it still works correctly?

No, I will have to uninstall and reinstall again after every reboot.

**Comment by sirbabyface** [comment]
I do have a similar same issue. The applications just doesn't start.

**Comment by glsorre** [comment]
hi! Could you check you have not deleted the 5 vdesktops?

**Comment by sirbabyface** [comment]
I do have the 5 virtual desktops.
![image](https://user-images.githubusercontent.com/223056/129330136-2d9a0bd0-3fd8-4aa8-ab42-06d60083ad67.png)

I've uninstalled and installed as suggested by @silver-dragon. BUt I'm attaching the errors I gor before in the Event Viewer

Faulting application name: AmethystWindowsSystray.exe, version: 1.0.21150.1, time stamp: 0xc46a19be
Faulting module name: KERNELBASE.dll, version: 10.0.19041.1151, time stamp: 0x5da51925
Exception code: 0xe0434352
Fault offset: 0x0012b512
Faulting process id: 0x5fd4
Faulting application start time: 0x01d7901dbc631d18
Faulting application path: C:\Program Files\WindowsApps\e7e2fe78-574a-47c3-81a2-66484cda1c60_1.0.21150.1_x64__wr4dg9c1cnpd8\AmethystWindowsSystray\AmethystWindowsSystray.exe
Faulting module path: C:\WINDOWS\System32\KERNELBASE.dll
Report Id: eb06008b-82ee-4b6f-a04c-4c91609747ac
Faulting package full name: e7e2fe78-574a-47c3-81a2-66484cda1c60_1.0.21150.1_x64__wr4dg9c1cnpd8
Faulting package-relative application ID: App

Application: AmethystWindowsSystray.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[DesktopWindowManager.Internal.Pair`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Vanara.PInvoke.HMONITOR, Vanara.PInvoke.Shared, Version=3.3.0.0, Culture=neutral, PublicKeyToken=c37e4080322237fa]], AmethystWindowsSystray, Version=1.0.21150.1, Culture=neutral, PublicKeyToken=null],[DesktopWindowManager.Internal.Layout, AmethystWindowsSystray, Version=1.0.21150.1, Culture=neutral, PublicKeyToken=null]].Insert(DesktopWindowManager.Internal.Pair`2<System.__Canon,Vanara.PInvoke.HMONITOR>, DesktopWindowManager.Internal.Layout, Boolean)
   at System.Linq.Enumerable.ToDictionary[[System.Collections.Generic.KeyValuePair`2[[DesktopWindowManager.Internal.Pair`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Vanara.PInvoke.HMONITOR, Vanara.PInvoke.Shared, Version=3.3.0.0, Culture=neutral, PublicKeyToken=c37e4080322237fa]], AmethystWindowsSystray, Version=1.0.21150.1, Culture=neutral, PublicKeyToken=null],[DesktopWindowManager.Internal.Layout, AmethystWindowsSystray, Version=1.0.21150.1, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[DesktopWindowManager.Internal.Pair`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Vanara.PInvoke.HMONITOR, Vanara.PInvoke.Shared, Version=3.3.0.0, Culture=neutral, PublicKeyToken=c37e4080322237fa]], AmethystWindowsSystray, Version=1.0.21150.1, Culture=neutral, PublicKeyToken=null],[DesktopWindowManager.Internal.Layout, AmethystWindowsSystray, Version=1.0.21150.1, Culture=neutral, PublicKeyToken=null]](System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<DesktopWindowManager.Internal.Pair`2<System.__Canon,Vanara.PInvoke.HMONITOR>,DesktopWindowManager.Internal.Layout>>, System.Func`2<System.Collections.Generic.KeyValuePair`2<DesktopWindowManager.Internal.Pair`2<System.__Canon,Vanara.PInvoke.HMONITOR>,DesktopWindowManager.Internal.Layout>,DesktopWindowManager.Internal.Pair`2<System.__Canon,Vanara.PInvoke.HMONITOR>>, System.Func`2<System.Collections.Generic.KeyValuePair`2<DesktopWindowManager.Internal.Pair`2<System.__Canon,Vanara.PInvoke.HMONITOR>,DesktopWindowManager.Internal.Layout>,DesktopWindowManager.Internal.Layout>, System.Collections.Generic.IEqualityComparer`1<DesktopWindowManager.Internal.Pair`2<System.__Canon,Vanara.PInvoke.HMONITOR>>)
   at AmethystWindowsSystray.DesktopWindowsManager.ReadLayouts()
   at AmethystWindowsSystray.DesktopWindowsManager.LoadLayouts()
   at AmethystWindowsSystray.SystrayContext+<Initialize>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by glsorre** [comment]
There is something not quite right with the way the I save and load the layouts for each vdesktop. Have you changed desktop names while amethyst was up? I think that scenario is not covered but I need a bit of time to check.

**Comment by sirbabyface** [comment]
I did change the names, after installing Amethyst. But once I've rebooted the virtual desktops were already created with the previous name. Not sure if that is a problem or not.
Also for me the problem has that no auto layout of windows was working. I need to check if I can get time to also help you looking at the code of this (maybe during holidays)

**Comment by glsorre** [comment]
@sirbabyface any help would be welcome.

**Comment by sirbabyface** [comment]
After the reboot this is the look of the Amethyst Windows:
![image](https://user-images.githubusercontent.com/223056/129521383-96c7d7a4-d3c0-4978-b189-56744b344951.png)

So it seems the windows list is not being returned. Error in the Event Viewer

```
Application: AmethystWindowsSystray.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException
   at System.ThrowHelper.ThrowArgumentException(System.ExceptionResource)
   at System.Collections.Generic.Dictionary`2[[DesktopWindowManager.Internal.Pair`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Vanara.PInvoke.HMONITOR, Vanara.PInvoke.Shared, Version=3.3.0.0, Culture=neutral, PublicKeyToken=c37e4080322237fa]], AmethystWindowsSystray, Version=1.0.21150.1, Culture=neutral, PublicKeyToken=null],[DesktopWindowManager.Internal.Layout, AmethystWindowsSystray, Version=1.0.21150.1, Culture=neutral, PublicKeyToken=null]].Insert(DesktopWindowManager.Internal.Pair`2<System.__Canon,Vanara.PInvoke.HMONITOR>, DesktopWindowManager.Internal.Layout, Boolean)
   at System.Linq.Enumerable.ToDictionary[[System.Collections.Generic.KeyValuePair`2[[DesktopWindowManager.Internal.Pair`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Vanara.PInvoke.HMONITOR, Vanara.PInvoke.Shared, Version=3.3.0.0, Culture=neutral, PublicKeyToken=c37e4080322237fa]], AmethystWindowsSystray, Version=1.0.21150.1, Culture=neutral, PublicKeyToken=null],[DesktopWindowManager.Internal.Layout, AmethystWindowsSystray, Version=1.0.21150.1, Culture=neutral, PublicKeyToken=null]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[DesktopWindowManager.Internal.Pair`2[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089],[Vanara.PInvoke.HMONITOR, Vanara.PInvoke.Shared, Version=3.3.0.0, Culture=neutral, PublicKeyToken=c37e4080322237fa]], AmethystWindowsSystray, Version=1.0.21150.1, Culture=neutral, PublicKeyToken=null],[DesktopWindowManager.Internal.Layout, AmethystWindowsSystray, Version=1.0.21150.1, Culture=neutral, PublicKeyToken=null]](System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<DesktopWindowManager.Internal.Pair`2<System.__Canon,Vanara.PInvoke.HMONITOR>,DesktopWindowManager.Internal.Layout>>, System.Func`2<System.Collections.Generic.KeyValuePair`2<DesktopWindowManager.Internal.Pair`2<System.__Canon,Vanara.PInvoke.HMONITOR>,DesktopWindowManager.Internal.Layout>,DesktopWindowManager.Internal.Pair`2<System.__Canon,Vanara.PInvoke.HMONITOR>>, System.Func`2<System.Collections.Generic.KeyValuePair`2<DesktopWindowManager.Internal.Pair`2<System.__Canon,Vanara.PInvoke.HMONITOR>,DesktopWindowManager.Internal.Layout>,DesktopWindowManager.Internal.Layout>, System.Collections.Generic.IEqualityComparer`1<DesktopWindowManager.Internal.Pair`2<System.__Canon,Vanara.PInvoke.HMONITOR>>)
   at AmethystWindowsSystray.DesktopWindowsManager.ReadLayouts()
   at AmethystWindowsSystray.DesktopWindowsManager.LoadLayouts()
   at AmethystWindowsSystray.SystrayContext+<Initialize>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_1(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

**Comment by glsorre** [comment]
I completely rewritten settings savings in v2 https://github.com/glsorre/amethystwindows/releases/tag/2.0.2.1 . Please try it.

**Comment by dordio** [comment]
Sorry I'm no longer using Windows 10, I've moved to Windows 11. I can say that it's working on Windows 11. There are some issues though.
It sometimes crashes without error, just closes.
You have duplicated hotkeys setup.
If you change the hotkeys and restart the app the change are reset to the original.

If you don't mind a sugestion: the ability to change the main modkey. I'd like to use the windows key as the modkey if possible, of course.

Thank you for all your work. I apreciate it very much.

**Comment by glsorre** [comment]
@dordio are you reporting on v2?

**Comment by dordio** [comment]
I am. I'm sorry I didn't mention that. I can open an issue in the correct place if you wish.

**Comment by glsorre** [comment]
I am investigating the hotkey issue and come back to you.

**Comment by glsorre** [comment]
@dordio https://github.com/glsorre/amethystwindows/releases/tag/2.0.3.1 could you try this build?
I have added crashes reporting as well to see if I can spot the errors you are talking about.

**Comment by dordio** [comment]
Sure, no problem I'll report back as soon as I can. Thank you.

**Comment by dordio** [comment]
This is what I've found so far:
- Moving windows between screens doesn't work
- Expand and shrink main pane doesn't work
- Moving focus between previous/next screen only works if the focus is on the secondary screen. If focus is on primary screen is does nothing. I've got a couple of crashes without errors while testing this.
- Swaping focus and moving focused window around works fine.
- Rotating layout also works fine.

If I find anything else I'll let you know.

**Comment by glsorre** [comment]
@dordio thanks will investigate and come back to you

**Comment by glsorre** [comment]
Hello @dordio! Couldyou try with https://github.com/glsorre/amethystwindows/releases/tag/2.0.4.1?
Also could you paste `%APPDATA%/Amethyst Windows/MySettings.json` here?

**Comment by dordio** [comment]
Hello @glsorre! Version 2.0.4.1 is having the same issues as before, but this time only after I restarted my PC. I tested all shortcuts and they worked fine, also no crashes. Once I restarted the PC and loaded the app all the previous problems came back.


As per your request here is the content of my MySettings.json:

> {"DesktopMonitors":[{"DesktopID":"0192cb74-78d3-4ac5-9cf1-2e743d6a78d4","MonitorX":0,"MonitorY":0,"Layout":3,"Factor":-8},{"DesktopID":"0192cb74-78d3-4ac5-9cf1-2e743d6a78d4","MonitorX":-1920,"MonitorY":0,"Layout":0,"Factor":0}],"Padding":10,"Step":25,"LayoutPadding":0,"MarginTop":10,"MarginRight":10,"MarginBottom":10,"MarginLeft":10,"VirtualDesktops":0,"Disabled":false,"Filters":[],"Additions":[],"Hotkeys":[{"Hotkey":{"Key":35,"Modifiers":1},"Command":"Rotate Layout Clockwise"},{"Hotkey":{"Key":18,"Modifiers":13},"Command":"rotateLayoutCounterclockwise"},{"Hotkey":{"Key":6,"Modifiers":5},"Command":"setMainPane"},{"Hotkey":{"Key":51,"Modifiers":5},"Command":"swapFocusedCounterclockwise"},{"Hotkey":{"Key":55,"Modifiers":5},"Command":"swapFocusedClockwise"},{"Hotkey":{"Key":53,"Modifiers":5},"Command":"swapFocusCounterclockwise"},{"Hotkey":{"Key":54,"Modifiers":5},"Command":"swapFocusClockwise"},{"Hotkey":{"Key":59,"Modifiers":5},"Command":"moveFocusPreviousScreen"},{"Hotkey":{"Key":57,"Modifiers":5},"Command":"moveFocusNextScreen"},{"Hotkey":{"Key":55,"Modifiers":13},"Command":"expandMainPane"},{"Hotkey":{"Key":51,"Modifiers":13},"Command":"shrinkMainPane"},{"Hotkey":{"Key":53,"Modifiers":7},"Command":"Move Focused Window Previous Screen"},{"Hotkey":{"Key":54,"Modifiers":7},"Command":"Move Focused Window Next Screen"},{"Hotkey":{"Key":69,"Modifiers":5},"Command":"redraw"},{"Hotkey":{"Key":23,"Modifiers":13},"Command":"moveFocusedNextSpace"},{"Hotkey":{"Key":25,"Modifiers":13},"Command":"moveFocusedPreviousSpace"},{"Hotkey":{"Key":35,"Modifiers":13},"Command":"moveFocusedToSpace1"},{"Hotkey":{"Key":36,"Modifiers":13},"Command":"moveFocusedToSpace2"},{"Hotkey":{"Key":37,"Modifiers":13},"Command":"moveFocusedToSpace3"},{"Hotkey":{"Key":38,"Modifiers":13},"Command":"moveFocusedToSpace4"},{"Hotkey":{"Key":39,"Modifiers":13},"Command":"moveFocusedToSpace5"},{"Hotkey":{"Key":18,"Modifiers":5},"Command":"rotateLayoutClockwise"},{"Hotkey":{"Key":18,"Modifiers":13},"Command":"rotateLayoutCounterclockwise"},{"Hotkey":{"Key":6,"Modifiers":5},"Command":"setMainPane"},{"Hotkey":{"Key":51,"Modifiers":5},"Command":"swapFocusedCounterclockwise"},{"Hotkey":{"Key":55,"Modifiers":5},"Command":"swapFocusedClockwise"},{"Hotkey":{"Key":53,"Modifiers":5},"Command":"swapFocusCounterclockwise"},{"Hotkey":{"Key":54,"Modifiers":5},"Command":"swapFocusClockwise"},{"Hotkey":{"Key":59,"Modifiers":5},"Command":"moveFocusPreviousScreen"},{"Hotkey":{"Key":57,"Modifiers":5},"Command":"moveFocusNextScreen"},{"Hotkey":{"Key":53,"Modifiers":7},"Command":"Expand Main Pane"},{"Hotkey":{"Key":51,"Modifiers":13},"Command":"shrinkMainPane"},{"Hotkey":{"Key":54,"Modifiers":7},"Command":"Move Focused Window Previous Screen"},{"Hotkey":{"Key":53,"Modifiers":5},"Command":"moveFocusedNextScreen"},{"Hotkey":{"Key":69,"Modifiers":5},"Command":"redraw"},{"Hotkey":{"Key":23,"Modifiers":13},"Command":"moveFocusedNextSpace"},{"Hotkey":{"Key":25,"Modifiers":13},"Command":"moveFocusedPreviousSpace"},{"Hotkey":{"Key":35,"Modifiers":13},"Command":"moveFocusedToSpace1"},{"Hotkey":{"Key":36,"Modifiers":13},"Command":"moveFocusedToSpace2"},{"Hotkey":{"Key":37,"Modifiers":13},"Command":"moveFocusedToSpace3"},{"Hotkey":{"Key":38,"Modifiers":13},"Command":"moveFocusedToSpace4"},{"Hotkey":{"Key":39,"Modifiers":13},"Command":"moveFocusedToSpace5"},{"Hotkey":{"Key":18,"Modifiers":5},"Command":"rotateLayoutClockwise"},{"Hotkey":{"Key":18,"Modifiers":13},"Command":"rotateLayoutCounterclockwise"},{"Hotkey":{"Key":6,"Modifiers":5},"Command":"setMainPane"},{"Hotkey":{"Key":51,"Modifiers":5},"Command":"swapFocusedCounterclockwise"},{"Hotkey":{"Key":55,"Modifiers":5},"Command":"swapFocusedClockwise"},{"Hotkey":{"Key":53,"Modifiers":5},"Command":"swapFocusCounterclockwise"},{"Hotkey":{"Key":54,"Modifiers":5},"Command":"swapFocusClockwise"},{"Hotkey":{"Key":59,"Modifiers":5},"Command":"moveFocusPreviousScreen"},{"Hotkey":{"Key":57,"Modifiers":5},"Command":"moveFocusNextScreen"},{"Hotkey":{"Key":55,"Modifiers":13},"Command":"expandMainPane"},{"Hotkey":{"Key":51,"Modifiers":13},"Command":"shrinkMainPane"},{"Hotkey":{"Key":53,"Modifiers":7},"Command":"Move Focused Window Previous Screen"},{"Hotkey":{"Key":54,"Modifiers":7},"Command":"Move Focused Window Next Screen"},{"Hotkey":{"Key":69,"Modifiers":5},"Command":"redraw"},{"Hotkey":{"Key":23,"Modifiers":13},"Command":"moveFocusedNextSpace"},{"Hotkey":{"Key":25,"Modifiers":13},"Command":"moveFocusedPreviousSpace"},{"Hotkey":{"Key":35,"Modifiers":13},"Command":"moveFocusedToSpace1"},{"Hotkey":{"Key":36,"Modifiers":13},"Command":"moveFocusedToSpace2"},{"Hotkey":{"Key":37,"Modifiers":13},"Command":"moveFocusedToSpace3"},{"Hotkey":{"Key":38,"Modifiers":13},"Command":"moveFocusedToSpace4"},{"Hotkey":{"Key":39,"Modifiers":13},"Command":"moveFocusedToSpace5"},{"Hotkey":{"Key":18,"Modifiers":5},"Command":"rotateLayoutClockwise"},{"Hotkey":{"Key":18,"Modifiers":13},"Command":"rotateLayoutCounterclockwise"},{"Hotkey":{"Key":6,"Modifiers":5},"Command":"setMainPane"},{"Hotkey":{"Key":51,"Modifiers":5},"Command":"Swap Focused Window Counterclockwise"},{"Hotkey":{"Key":55,"Modifiers":5},"Command":"Swap Focused Window Clockwise"},{"Hotkey":{"Key":53,"Modifiers":5},"Command":"swapFocusCounterclockwise"},{"Hotkey":{"Key":54,"Modifiers":5},"Command":"swapFocusClockwise"},{"Hotkey":{"Key":59,"Modifiers":5},"Command":"moveFocusPreviousScreen"},{"Hotkey":{"Key":57,"Modifiers":5},"Command":"moveFocusNextScreen"},{"Hotkey":{"Key":55,"Modifiers":13},"Command":"expandMainPane"},{"Hotkey":{"Key":51,"Modifiers":13},"Command":"shrinkMainPane"},{"Hotkey":{"Key":53,"Modifiers":7},"Command":"Move Focused Window Previous Screen"},{"Hotkey":{"Key":54,"Modifiers":7},"Command":"Move Focused Window Next Screen"},{"Hotkey":{"Key":69,"Modifiers":5},"Command":"redraw"},{"Hotkey":{"Key":23,"Modifiers":13},"Command":"moveFocusedNextSpace"},{"Hotkey":{"Key":25,"Modifiers":13},"Command":"moveFocusedPreviousSpace"},{"Hotkey":{"Key":35,"Modifiers":13},"Command":"moveFocusedToSpace1"},{"Hotkey":{"Key":36,"Modifiers":13},"Command":"moveFocusedToSpace2"},{"Hotkey":{"Key":37,"Modifiers":13},"Command":"moveFocusedToSpace3"},{"Hotkey":{"Key":38,"Modifiers":13},"Command":"moveFocusedToSpace4"},{"Hotkey":{"Key":39,"Modifiers":13},"Command":"moveFocusedToSpace5"},{"Hotkey":{"Key":18,"Modifiers":5},"Command":"rotateLayoutClockwise"},{"Hotkey":{"Key":18,"Modifiers":13},"Command":"rotateLayoutCounterclockwise"},{"Hotkey":{"Key":6,"Modifiers":5},"Command":"setMainPane"},{"Hotkey":{"Key":51,"Modifiers":5},"Command":"swapFocusedCounterclockwise"},{"Hotkey":{"Key":55,"Modifiers":5},"Command":"swapFocusedClockwise"},{"Hotkey":{"Key":53,"Modifiers":5},"Command":"swapFocusCounterclockwise"},{"Hotkey":{"Key":54,"Modifiers":5},"Command":"swapFocusClockwise"},{"Hotkey":{"Key":59,"Modifiers":5},"Command":"moveFocusPreviousScreen"},{"Hotkey":{"Key":57,"Modifiers":5},"Command":"moveFocusNextScreen"},{"Hotkey":{"Key":55,"Modifiers":13},"Command":"expandMainPane"},{"Hotkey":{"Key":51,"Modifiers":13},"Command":"shrinkMainPane"},{"Hotkey":{"Key":54,"Modifiers":5},"Command":"moveFocusedPreviousScreen"},{"Hotkey":{"Key":53,"Modifiers":5},"Command":"moveFocusedNextScreen"},{"Hotkey":{"Key":69,"Modifiers":5},"Command":"redraw"},{"Hotkey":{"Key":23,"Modifiers":13},"Command":"moveFocusedNextSpace"},{"Hotkey":{"Key":25,"Modifiers":13},"Command":"moveFocusedPreviousSpace"},{"Hotkey":{"Key":35,"Modifiers":13},"Command":"moveFocusedToSpace1"},{"Hotkey":{"Key":36,"Modifiers":13},"Command":"moveFocusedToSpace2"},{"Hotkey":{"Key":37,"Modifiers":13},"Command":"moveFocusedToSpace3"},{"Hotkey":{"Key":38,"Modifiers":13},"Command":"moveFocusedToSpace4"},{"Hotkey":{"Key":39,"Modifiers":13},"Command":"moveFocusedToSpace5"}]}

**Comment by glsorre** [comment]
@dordio I think I can see your problem and my error 🤦. Will come back to you.

**Comment by glsorre** [comment]
@dordio I have done many tests but I have not been able to modify `MySettings.json` with more than 21 entries as you have at the moment. It is possible is due to a bug in a previous version.

Could you please remove the file and restart from the scratch with version `2.0.4.1` and see what happens?
This means you will need to reset your preferences.

**Comment by dordio** [comment]
@glsorre so far so good! 😁👍
Apart from one crash while trying to "swap focused window" on my secondary monitor everything seems to be working correctly. Tried a few reboots and still working.

I'll get back to you if something changes.
Thank you very much for all you've done. Great work!

In the mean time I've noticed a couple of "bugs". Minor stuff. I'll post about them in the correct page so you can take a look when you get the time. No rush.
