### ISSUE TITLE
Cannot run on Win11

### ISSUE THREAD

**Issue by xcloudx01** [glsorre/amethystwindows#86]
After opening AmethystWindows.exe I see the icon in the tray area appear, my mouse cursor indicates some activity, then the icon disappears and the process closes. I've tried running earlier builds but the problem remains

**Comment by schmic** [comment]
It won't help much with your issue but I was just able to install and run on Win11.
WIth the latest download as of today.

**Comment by boorac** [comment]
I have the same issue with the x86 and x64 msi

**Comment by maciej-makowski** [comment]
I checked out the latest code crashes on Windows 11 Pro

![image](https://user-images.githubusercontent.com/377311/193475892-13a80733-2ac4-4ee2-b9fc-408746efec40.png)

Seems to be a problem in VirtualDesktop dependency on sam COM Interop issue. 

```
Exception has occurred: CLR/System.Collections.Generic.KeyNotFoundException
An unhandled exception of type 'System.Collections.Generic.KeyNotFoundException' occurred in System.Private.CoreLib.dll: 'The given key 'IApplicationView' was not present in the dictionary.'
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at WindowsDesktop.Interop.ComInterfaceAssemblyBuilder.CreateAssembly() in C:\Users\macie\Projects\VirtualDesktop\src\VirtualDesktop\Interop\ComInterfaceAssemblyBuilder.cs:line 136
   at WindowsDesktop.Interop.ComInterfaceAssemblyBuilder.GetAssembly() in C:\Users\macie\Projects\VirtualDesktop\src\VirtualDesktop\Interop\ComInterfaceAssemblyBuilder.cs:line 37
   at WindowsDesktop.VirtualDesktop.InitializeCore() in C:\Users\macie\Projects\VirtualDesktop\src\VirtualDesktop\VirtualDesktop.system.cs:line 95
   at WindowsDesktop.VirtualDesktop.InitializeIfNeeded() in C:\Users\macie\Projects\VirtualDesktop\src\VirtualDesktop\VirtualDesktop.system.cs:line 83
   at WindowsDesktop.VirtualDesktop.FromHwnd(IntPtr hWnd) in C:\Users\macie\Projects\VirtualDesktop\src\VirtualDesktop\VirtualDesktop.cs:line 173
   at AmethystWindows.DesktopWindowsManager.DesktopWindow.GetVirtualDesktop() in C:\Users\macie\Projects\amethystwindows\AmethystWindows\DesktopWindowsManager\DesktopWindow.cs:line 157
   at AmethystWindows.DesktopWindowsManager.DesktopWindow.GetInfo() in C:\Users\macie\Projects\amethystwindows\AmethystWindows\DesktopWindowsManager\DesktopWindow.cs:line 132
   at AmethystWindows.DesktopWindowsManager.DesktopWindowsManager.<CollectWindows>b__30_0(HWND windowHandle, IntPtr lparam) in C:\Users\macie\Projects\amethystwindows\AmethystWindows\DesktopWindowsManager\DesktopWindowManager.windows.cs:line 89
   at Vanara.PInvoke.User32.EnumWindows(EnumWindowsProc lpEnumFunc, IntPtr lParam)
   at AmethystWindows.DesktopWindowsManager.DesktopWindowsManager.CollectWindows() in C:\Users\macie\Projects\amethystwindows\AmethystWindows\DesktopWindowsManager\DesktopWindowManager.windows.cs:line 113
   at AmethystWindows.App.App_Activated(Object sender, EventArgs e) in C:\Users\macie\Projects\amethystwindows\AmethystWindows\App.xaml.cs:line 34
   at System.Windows.Application.OnActivated(EventArgs e)
   at System.Windows.Application.WmActivateApp(Int32 wParam)
   at System.Windows.Application.AppFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

Did some poking around, looks like https://github.com/Grabacr07/VirtualDesktop/issues/76.

**Comment by azinsharaf** [comment]
same issue on my machine (Win 11, VM using Parallel on Mac M1)

```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎9/‎21/‎2022
OS build	22621.521
Experience	Windows Feature Experience Pack 1000.22634.1000.0
```

**Comment by glsorre** [comment]
You should try to delete `%APPDATA%/Amethyst Windows/MySettings.json`. It is a known bug...I just need the time to release the fix. :(

**Comment by azinsharaf** [comment]
i couldn't find `Mysettings.json` file on my machine. I used msi_x64 installer file (v 2.0.4.1).

**Comment by maciej-makowski** [comment]
If you're on Windows 11 build > 22000 or Windos 10 build > 17134, I think you're hitting a problem in a dependency I've mentioned earlier. 

I've sent a PR with the fix to them: https://github.com/Grabacr07/VirtualDesktop/pull/79, but no idea how long it will take to accept it and propagate the change to this project.

There is an elaborate way to test/apply this before `VirtualDesktop` maintaniers merge it and it propagates to this project. I'm happy to provide more details if anyone is interested in building the dependency themselves and testing the fix.

**Comment by azinsharaf** [comment]
@maciej-makowski  
So is it a Win issue for build> 22000?

**Comment by azinsharaf** [comment]
anybody knows when we can use amethyst on win 11 (build > 22000)?

**Comment by glsorre** [comment]
hello all, I have time to work on this project during holidays unfortunately...please try 2.0.196.1

**Comment by azinsharaf** [comment]
hi, i tried `2.0.196.1 Beta` but still doesn't work.
- the application's icon is blank.
![image](https://user-images.githubusercontent.com/10101468/209476723-85e6455f-7739-41b1-83c2-78dc9aa4ad98.png)

- nothing happens after launching the app. no tray icon.  

OS: `Windows 11 Pro - 22H2- ARM based`

**Comment by glsorre** [comment]
@azinsharaf the msi is x64 only...not even sure why it left you install :O

**Comment by acorazza** [comment]
I have the same problem as @azinsharaf but on x64. I installed Amethyst and it appears in my installed apps, but all I have is that blank shortcut in the start menu folder. The app doesn't start up.
