### ISSUE TITLE
Crashes on Startup

### ISSUE THREAD

**Issue by tryjude** [glsorre/amethystwindows#94]
I just installed Version 2.0.222.1 on Windows 10 using the asset listed under the Releases section of this github project. Installation succeeded but when I launch it I see the pink diamond for a couple of seconds on the taskbar and then it disappears. Appears to be crashing. I downloaded the latest release I could find.

This in the **error in the Windows event viewer** (see further below for exception details):

Faulting application name: AmethystWindows.exe, version: 1.0.0.0, time stamp: 0x6355849f
Faulting module name: KERNELBASE.dll, version: 10.0.19041.2486, time stamp: 0xca518c9d
Exception code: 0xc000041d
Fault offset: 0x0012e292
Faulting process id: 0x2754
Faulting application start time: 0x01d937ff80e3700a
Faulting application path: C:\Program Files\WindowsApps\f04c436a-4cda-455d-b409-4520a608c6d0_2.0.222.1_neutral__wbnnev551gwxy\AmethystWindows\AmethystWindows.exe
Faulting module path: C:\Windows\System32\KERNELBASE.dll
Report Id: ae755013-aef6-41ad-80b3-cefe66c3ac4e
Faulting package full name: f04c436a-4cda-455d-b409-4520a608c6d0_2.0.222.1_neutral__wbnnev551gwxy
Faulting package-relative application ID: App

**Application Exception (separate event in EV):**

Application: AmethystWindows.exe
CoreCLR Version: 6.0.1122.52304
.NET Version: 6.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NotImplementedException: The method or operation is not implemented.
   at WindowsDesktop.Interop.IServiceProvider.QueryService(Guid& guidService, Guid& riid)
   at WindowsDesktop.Interop.ComInterfaceAssembly.CreateInstance(Type type, Nullable`1 guidService)
   at WindowsDesktop.Interop.ComInterfaceAssembly.CreateInstance(String comInterfaceName)
   at WindowsDesktop.Interop.ComWrapperBase`1..ctor(ComInterfaceAssembly assembly)
   at WindowsDesktop.Interop.Build10240.ApplicationViewCollection..ctor(ComInterfaceAssembly assembly)
   at WindowsDesktop.Interop.Build10240.VirtualDesktopProvider10240.InitializeCore(ComInterfaceAssembly assembly)
   at WindowsDesktop.Interop.VirtualDesktopProvider.Initialize(ComInterfaceAssembly assembly)
   at WindowsDesktop.VirtualDesktop.InitializeCore()
   at WindowsDesktop.VirtualDesktop.InitializeIfNeeded()
   at WindowsDesktop.VirtualDesktop.FromHwnd(IntPtr hWnd)
   at AmethystWindows.DesktopWindowsManager.DesktopWindow.GetVirtualDesktop()
   at AmethystWindows.DesktopWindowsManager.DesktopWindow.GetInfo()
   at AmethystWindows.DesktopWindowsManager.DesktopWindowsManager.<CollectWindows>b__32_0(HWND windowHandle, IntPtr lparam)
   at Vanara.PInvoke.User32.EnumWindows(EnumWindowsProc lpEnumFunc, IntPtr lParam)
   at AmethystWindows.DesktopWindowsManager.DesktopWindowsManager.CollectWindows()
   at AmethystWindows.App.App_Activated(Object sender, EventArgs e)
   at System.Windows.Application.OnActivated(EventArgs e)
   at System.Windows.Application.WmActivateApp(Int32 wParam)
   at System.Windows.Application.AppFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

**Comment by sschneider-ihre-pvs** [comment]
same here
